global:

    # Basic parameters
    output_folder: exp/TIMIT_CTC
    device: cuda
    sample_rate: 16000
    seed: 1234
    verbosity: 2

    # Data files
    data_file: /network/tmp1/plantinp/data/TIMIT.tar.gz
    local_data_folder: /tmp/timit_experiment
    csv_train: $local_data_folder/train.csv
    csv_valid: $local_data_folder/dev.csv
    csv_test: $local_data_folder/test.csv

    # Computation files
    training_computations: cfg/end2end_ASR/CTC/TIMIT/training_loop.cfg
    feature_computations: cfg.features.mfcc_features.mfcc_features
    neural_computations: cfg/end2end_ASR/CTC/TIMIT/basic_GRU.cfg

    # Neural Parameters
    N_epochs: 28
    N_batch: 16
    lr: 0.0005

    # Other Parameters
    sample_rate: 16000
    seed: 456

# experiment.py
copy_locally:
    class_name: speechbrain.data_io.data_preparation.copy_data_locally
    data_file: $data_file
    local_folder: $local_data_folder

prepare_timit:
    class_name: speechbrain.data_io.data_preparation.timit_prepare
    data_folder: $local_data_folder
    splits:
        - train
        - dev
        - test
    save_folder: $local_data_folder

training_nn:
    class_name: speechbrain.core.execute_computations
    cfg_file: $training_computations
    device: $device
    n_loops: $N_epochs
    recovery: True

test:
    class_name: speechbrain.core.execute_computations
    cfg_file: $neural_computations
    csv_file: $csv_test
    csv_read:
        - wav
        - phn
    device: $device
    batch_size: 1
    stop_at: print_predictions
    out_var:
        - loss
        - wer
    accum_type:
        - average
        - average
    sentence_sorting: ascending
    torch_no_grad: True
    eval_mode: True
