# ################################
# Model: Wav2Vec + DNN + CTC + Softmax
# Authors modifier: Gaelle Laperriere
# ################################

# ------ Paths and parameters

# Seed needs to be set at top of yaml, before objects with parameters are made.
seed: 4242
__set_seed: !!python/object/apply:torch.manual_seed [!ref <seed>]
output_folder: !ref results/media_SLU_wav2vec_full/<seed>
cer_file_test: !ref <output_folder>/cer_test.txt
ctc_file_test: !ref <output_folder>/ctc_test.txt
coer_file_test: !ref <output_folder>/coer_test.txt
cver_file_test: !ref <output_folder>/cver_test.txt
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt

# See https://github.com/pytorch/fairseq/blob/main/examples/wav2vec/README.md
# for Wav2Vec models and https://huggingface.co/LeBenchmark for Franch ones.
wav2vec_url: LeBenchmark/wav2vec2-FR-3K-large

# Data files:
data_folder: !PLACEHOLDER
csv_train: !ref <data_folder>/train.csv
csv_valid: !ref <data_folder>/dev.csv
csv_test: !ref <data_folder>/test.csv

# Data parameters:
# With data_parallel batch_size is split into N jobs.
# With DDP batch_size is multiplied by N jobs.
batch_size: 4
test_batch_size: 2
# We remove utterance slonger than 8s in the train/dev/test sets as
# longer sentences certainly correspond to "open microphones".
avoid_if_longer_than: 90.0
avoid_if_smaller_than: 0.0
dataloader_options:
    batch_size: !ref <batch_size>
    num_workers: 3
    shuffle: True
test_dataloader_options:
    batch_size: !ref <test_batch_size>
    num_workers: 3

# Feature parameters:
sample_rate: 16000
feats_dim: 1024

# Training parameters:
number_of_epochs: 78
lr: 1
lr_wav2vec: 0.0001
annealing_factor: 0.8
annealing_factor_wav2vec: 0.9
improvement_threshold: 0.0025
improvement_threshold_wav2vec: 0.0025
patient: 0
patient_wav2vec: 0
sorting: random

# Model parameters:
activation: !name:torch.nn.LeakyReLU
dropout: 0.15
cnn_blocks: 0
rnn_layers: 0
dnn_blocks: 3
rnn_neurons: 0
dnn_neurons: 512

# Wav2Vec parameters:
freeze: False

# Decoding parameters:
blank_index: 0

# Outputs:
output_neurons: 187

# ------ Functions and classes

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>

wav2vec: !new:speechbrain.lobes.models.huggingface_wav2vec.HuggingFaceWav2Vec2
    source: !ref <wav2vec_url>
    output_norm: True
    freeze: !ref <freeze>
    save_path: !ref <save_folder>/wav2vec.pt

dec: !new:speechbrain.lobes.models.VanillaNN.VanillaNN
    input_shape: [null, null, !ref <feats_dim>]
    activation: !ref <activation>
    dnn_blocks : !ref <dnn_blocks>
    dnn_neurons: !ref <dnn_neurons>

output_lin: !new:speechbrain.nnet.linear.Linear
    input_size: !ref <dnn_neurons>
    n_neurons: !ref <output_neurons>
    bias: True

softmax: !new:speechbrain.nnet.activations.Softmax
    apply_log: True

ctc_cost: !name:speechbrain.nnet.losses.ctc_loss
    blank_index: !ref <blank_index>

modules:
    wav2vec: !ref <wav2vec>
    dec: !ref <dec>
    output_lin: !ref <output_lin>

model: !new:torch.nn.ModuleList
    - [!ref <dec>, !ref <output_lin>]

model_wav2vec: !new:torch.nn.ModuleList
    - [!ref <wav2vec>]

opt_class: !name:torch.optim.Adadelta
    lr: !ref <lr>
    rho: 0.95
    eps: 1.e-8

opt_class_wav2vec: !name:torch.optim.Adam
   lr: !ref <lr_wav2vec>

lr_annealing: !new:speechbrain.nnet.schedulers.NewBobScheduler
    initial_value: !ref <lr>
    improvement_threshold: !ref <improvement_threshold>
    annealing_factor: !ref <annealing_factor>
    patient: !ref <patient>

lr_annealing_wav2vec: !new:speechbrain.nnet.schedulers.NewBobScheduler
    initial_value: !ref <lr_wav2vec>
    improvement_threshold: !ref <improvement_threshold_wav2vec>
    annealing_factor: !ref <annealing_factor_wav2vec>
    patient: !ref <patient_wav2vec>

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        model: !ref <model>
        wav2vec: !ref <wav2vec>
        lr_annealing: !ref <lr_annealing>
        lr_annealing_wav2vec: !ref <lr_annealing_wav2vec>
        counter: !ref <epoch_counter>

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>

ctc_computer: !name:speechbrain.utils.metric_stats.MetricStats
    metric: !name:speechbrain.nnet.losses.ctc_loss
        blank_index: !ref <blank_index>
        reduction: batch

error_rate_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats

cer_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats

coer_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats
    keep_concepts: True

cver_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats
    keep_concepts_values: True

# Tag list:
tag_list: <chambre-equipement>,<chambre-fumeur>,<chambre-standing>,<chambre-type>,<chambre-voisine>,<command-dial>,<command-tache>,<comparatif>,<comparatif-nombre>,<comparatif-paiement>,<comparatif-temps>,<connectattr>,<connectprop>,<evenement>,<hotel-etat-complet>,<hotel-etat-ferme>,<hotel-etoile>,<hotel-marque>,<hotel-marque-reservation>,<hotel-parking>,<hotel-services>,<lienref-codom>,<lienref-coref>,<lienref-elsens>,<localisation-arrondissement>,<localisation-arrondissement-hotel>,<localisation-cardinal>,<localisation-cardinal-hotel>,<localisation-codepostal>,<localisation-departement>,<localisation-departement-hotel>,<localisation-distancerelative>,<localisation-distancerelative-hotel>,<localisation-hotel-fin>,<localisation-lieurelatif-general>,<localisation-lieurelatif-general-hotel>,<localisation-lieurelatif-nomme>,<localisation-lieurelatif-nomme-hotel>,<localisation-pays>,<localisation-quartier>,<localisation-quartier-hotel>,<localisation-region>,<localisation-region-hotel>,<localisation-rue>,<localisation-rue-hotel>,<localisation-ville>,<localisation-ville-debut>,<localisation-ville-etape>,<localisation-ville-fin>,<localisation-ville-hotel>,<localisation-ville-hotel-debut>,<localisation-ville-hotel-etape>,<localisation-ville-hotel-fin>,<nom>,<nombre>,<nombre-chambre>,<nombre-chambre-disponible>,<nombre-chambre-disponible-reservation>,<nombre-chambre-hotel-reservation>,<nombre-chambre-reservation>,<nombre-debut>,<nombre-fin>,<nombre-hotel>,<nombre-hotel-reservation>,<nombrenondigit>,<nombrenondigit-hotel>,<nombrenondigit-hotel-reservation>,<nombrenondigit-reservation>,<nombre-reservation>,<nombre-restaurant>,<nombre-temps>,<nombre-temps-reservation>,<nom-client-hotel>,<nom-hotel>,<objet>,<objetbd>,<paiement-methodedepaiement>,<paiement-methodedepaiement-reservation>,<paiement-monnaie>,<paiement-montant-entier>,<paiement-montant-entier-chambre>,<paiement-montant-entier-reservation>,<paiement-montant-entier-reservation-chambre>,<paiement-montantqualitatif>,<paiement-montantqualitatif-chambre>,<paiement-montantqualitatif-reservation>,<paiement-montantqualitatif-reservation-chambre>,<personne-nomdefamille>,<rang>,<rang-hotel>,<rang-hotel-reservation>,<rang-reservation>,<rang-temps>,<rang-temps-reservation>,<reponse>,<sejour-nbadulte>,<sejour-nbadulte-reservation>,<sejour-nbcouple>,<sejour-nbcouple-reservation>,<sejour-nbenfant>,<sejour-nbenfant-reservation>,<sejour-nblitbebe>,<sejour-nblitbebe-reservation>,<sejour-nbnuit>,<sejour-nbnuit-reservation>,<sejour-nbpersonne>,<sejour-nbpersonne-reservation>,<temps-annee>,<temps-annee-debut>,<temps-annee-debut-reservation>,<temps-annee-fin>,<temps-annee-fin-reservation>,<temps-annee-reservation>,<temps-axetps>,<temps-axetps-reservation>,<temps-date>,<temps-date-debut>,<temps-date-debut-reservation>,<temps-date-fin>,<temps-date-fin-reservation>,<temps-daterelative-reservation>,<temps-date-reservation>,<temps-heure>,<temps-heure-fin>,<temps-heure-fin-reservation>,<temps-jourferie>,<temps-jourferie-debut>,<temps-jourferie-fin>,<temps-jourferie-reservation>,<temps-jour-mois>,<temps-jour-mois-debut>,<temps-jour-mois-debut-reservation>,<temps-jour-mois-fin>,<temps-jour-mois-fin-reservation>,<temps-jour-mois-reservation>,<temps-jour-semaine>,<temps-jour-semaine-debut>,<temps-jour-semaine-fin>,<temps-jour-semaine-reservation>,<temps-mois>,<temps-mois-debut>,<temps-mois-reservation>,<temps-plagerelative>,<temps-plagerelative-reservation>,<temps-plagetps>,<temps-plagetps-debut>,<temps-plagetps-debut-reservation>,<temps-plagetps-reservation>,<temps-unite>,<temps-unite-reservation>,<unknown>
