global:
    verbosity: 2
    output_folder: exp/minimal/process
    data_folder: samples/audio_samples
    csv_file: $data_folder/csv_example.csv
    sample_rate: 16000

functions:
    sample_data: !speechbrain.data_io.data_io.create_dataloader
        csv_file: $csv_file
        batch_size: 2
        csv_read: [wav]
    add_babble: !speechbrain.processing.speech_augmentation.add_babble
        snr_low: 10
        snr_high: 10
    add_reverb: !speechbrain.processing.speech_augmentation.add_reverb
        csv_file: samples/rir_samples/rirs.csv
    add_noise: !speechbrain.processing.speech_augmentation.add_noise
        snr_low: 10
        snr_high: 10
    add_noise_csv: !speechbrain.processing.speech_augmentation.add_noise
        csv_file: samples/noise_samples/noise.csv
        snr_low: 10
        snr_high: 10
    drop_freq: !speechbrain.processing.speech_augmentation.drop_freq
    drop_chunk: !speechbrain.processing.speech_augmentation.drop_chunk
    do_clip: !speechbrain.processing.speech_augmentation.do_clip
    speed_perturb: !speechbrain.processing.speech_augmentation.speed_perturb
        orig_freq: !$ <constants.sample_rate>
        speeds: [9, 11]
    save: !speechbrain.data_io.data_io.save
        sampling_rate: !$ <constants.sample_rate>
        save_format: flac
        parallel_write: True
