###################################################
# TO BE DONE
#
# Author
# ------
# Francesco Paissan, 2021
###################################################
seed: 1234
__set_torchseed: !apply:torch.manual_seed [!ref <seed>]

# DIRECTORIES
data_folder: !PLACEHOLDER  #'/path/to/BNCI2014001'. The dataset will be automatically downloaded in this folder
output_folder: !ref results/MOABB/PodNet_Nakanishi2015/<seed>

# DATASET HPARS
# Defining the MOABB dataset.
dataset: !new:moabb.datasets.Nakanishi2015
subject_list: ~  # subject list
n_classes: 12
sf: 250  # Target sampling rate (Hz)
# tmin, tmax respect to stimulus onset that define the interval attribute of the dataset class
# trial begins (0 s), cue (2 s, 1.25 s long); each trial is 6 s long
# dataset interval starts from 2
# -->tmin tmax are referred to this start value (e.g., tmin=0.5 corresponds to 2.5 s)
tmin: 0
tmax: ~
T: 1039 #!ref <sf> * (<tmax> - <tmin>)
# fmin, fmax band-pass filtering
fmin: 1
fmax: 120
channels: ~
C: 8
# Defining the MOABB paradigm and setting the pre-processing hyper-parameters for the specific dataset.
paradigm: !new:moabb.paradigms.SSVEP
  # events: !ref <events>
  n_classes: !ref <n_classes>
  fmin: !ref <fmin>
  fmax: !ref <fmax>
  tmin: !ref <tmin>
  tmax: !ref <tmax>
  channels: !ref <channels>
  resample: !ref <sf>


# TRAINING HPARS
num_parallel_processes: 2  # number of parallel processes to run
nfolds: 4 # number of cross-validation folds (only for within_session_it, cross_session_it)
number_of_epochs: 50 # number of training epochs
lr: 0.001 # learning rate


loss: !name:torch.nn.functional.nll_loss
optimizer: !name:torch.optim.Adam
  lr: !ref <lr>
epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter  # epoch counter
  limit: !ref <number_of_epochs>
batch_size: 32
valid_ratio: 0.2

# data iterators
within_session_it: !new:recipes.MOABB.dataio_iterators.WithinSession
  paradigm: !ref <paradigm>
  nfolds: !ref <nfolds>
  seed: !ref <seed>
leave_one_session_out_it: !new:recipes.MOABB.dataio_iterators.LeaveOneSessionOut
  paradigm: !ref <paradigm>
  seed: !ref <seed>
cross_session_it: !new:recipes.MOABB.dataio_iterators.CrossSession
  paradigm: !ref <paradigm>
  nfolds: !ref <nfolds>
  seed: !ref <seed>
leave_one_subject_out_it: !new:recipes.MOABB.dataio_iterators.LeaveOneSubjectOut
  paradigm: !ref <paradigm>
  seed: !ref <seed>

data_iterators: [
  !ref <within_session_it>,
  # !ref <leave_one_session_out_it>,
  !ref <cross_session_it>,
  !ref <leave_one_subject_out_it>,
]

input_shape: [null, !ref <T>, !ref <C>, null]
n_pods: 1
dense_max_norm: 0.5  # kernel max-norm constaint of the dense layer
dropout: 0.5  # dropout rate
filters_per_pod: 100  # n. of filters for pod convolutions

model: !new:speechbrain.lobes.models.PodNet.PodNet
  input_shape: !ref <input_shape>
  n_pods: !ref <n_pods>
  dense_n_neurons: !ref <n_classes>
  dense_max_norm: !ref <dense_max_norm>
  filters_pod: !ref <filters_per_pod>
  dropout: !ref <dropout>

test_with: 'best' # 'last' or 'best'
test_keys: ["acc"] # Possible opts: "loss", "f1", "auc", "acc"
avg_models: 1 # checkpoints to average

# Learning rate scheduling (cyclic learning rate is used here)
max_lr: !ref <lr> # Upper bound of the cycle (max value of the lr)
base_lr: 0.00000001 # Lower bound in the cycle (min value of the lr)
step_size: 100 # number of training iterations per half cycle (lower step_size => faster cycles)

lr_annealing: !new:speechbrain.nnet.schedulers.CyclicLRScheduler
  base_lr: !ref <base_lr>
  max_lr: !ref <max_lr>
  step_size: !ref <step_size>
